version: '3.7'

networks:
  backend:
    name: backend
    driver: bridge

services:
  registry-frontend:
    build:
        context: "."
    environment:
      - API_URL=http://localhost:3000/api
      - OIDC_ISSUER=http://localhost:5556/dex
      - OIDC_WELL_KNOWN=http://localhost:5556/dex
      - OIDC_CLIENT_ID=registry-frontend
    ports:
      - 8080:8080
    networks:
      - backend
