export enum SensorTheme {
    Energy = 'Energy',
    Agriculture = 'Agriculture',
    Transport = 'Transport',
    Waste = 'Waste',
    SoilAndUnderground = 'SoilAndUnderground',
    Sound = 'Sound',
    EnvironmentalChange = 'EnvironmentalChange',
    Air = 'Air',
    NatureAndLandscape = 'NatureAndLandscape',
    Water = 'Water',
    Safety = 'Safety',
    SpatialPlanning = 'SpatialPlanning',
    Watermanagement = 'Watermanagement',
    Aviation = 'Aviation',
    PublicTransport = 'PublicTransport',
    RailAndRoadTraffic = 'RailAndRoadTraffic',
    Shipping = 'Shipping',
    Construction = 'Construction',
    Housing = 'Housing',
    Health = 'Health',
}

export const SensorThemeTranslation = {
    Energy: $localize`:@@theme.energy:Energy`,
    Agriculture: $localize`:@@theme.agriculture:Agriculture`,
    Transport: $localize`:@@theme.transport:Transport`,
    Waste: $localize`:@@theme.waste:Waste`,
    SoilAndUnderground: $localize`:@@theme.soilandunderground:SoilAndUnderground`,
    Sound: $localize`:@@theme.sound:Sound`,
    EnvironmentalChange: $localize`:@@theme.environmentalchange:EnvironmentalChange`,
    Air: $localize`:@@theme.air:Air`,
    NatureAndLandscape: $localize`:@@theme.natureandlandscape:NatureAndLandscape`,
    Water: $localize`:@@theme.water:Water`,
    Safety: $localize`:@@theme.safety:Safety`,
    SpatialPlanning: $localize`:@@theme.spatialplanning:SpatialPlanning`,
    Watermanagement: $localize`:@@theme.watermanagement:Watermanagement`,
    Aviation: $localize`:@@theme.aviation:Aviation`,
    PublicTransport: $localize`:@@theme.publictransport:PublicTransport`,
    RailAndRoadTraffic: $localize`:@@theme.railandroadtraffic:RailAndRoadTraffic`,
    Shipping: $localize`:@@theme.shipping:Shipping`,
    Construction: $localize`:@@theme.construction:Construction`,
    Housing: $localize`:@@theme.housing:Housing`,
    Health: $localize`:@@theme.health:Health`,
};
