export enum Category {
    Beacon = 'Beacon',
    Sensor = 'Sensor',
    Camera = 'Camera',
}

const CategoryTranslation = {
  Beacon: $localize`:@@type.beacon:Beacon`,
  Sensor: $localize`:@@type.sensor:Sensor`,
  Camera: $localize`:@@type.camera:Camera`,
};

export function getCategoryTranslation(category) {
    return CategoryTranslation[category] ? CategoryTranslation[category] : category;
}

const SoundSensorTypes = [
  'Pickup',
  'Geophone',
  'Microphone',
  'Hydrophone',
  'Seismometer',
  'Sound locator',
  'SoundLevelMeter',
];

const ChemicalSensorTypes = [
  'Breathalyzer',
  'Carbon dioxide sensor',
  'Carbon monoxide detector',
  'Catalytic bead sensor',
  'Chemical field-effect transistor',
  'Chemiresistor',
  'Electrochemical gas sensor',
  'Electronic nose',
  'Electrolyte–insulator–semiconductor sensor',
  'Energy-dispersive X-ray spectroscopy',
  'Fluorescent chloride sensors',
  'Holographic sensor',
  'Hydrocarbon dew point analyzer',
  'Hydrogen sensor',
  'Hydrogen sulfide sensor',
  'Infrared point sensor',
  'Ion-selective electrode',
  'ISFET',
  'Nondispersive infrared sensor',
  'Microwave chemistry sensor',
  'Nitrogen oxide sensor',
  'Olfactometer',
  'Optode',
  'Oxygen sensor',
  'Ozone monitor',
  'Pellistor',
  'pH glass electrode',
  'Potentiometric sensor',
  'Redox electrode',
  'Smoke detector',
  'Zinc oxide nanorod sensor',
];

const ElectricCurrentSensorTypes = [
  'Current sensor',
  'Daly detector',
  'Electroscope',
  'Electron multiplier',
  'Faraday cup',
  'Galvanometer',
  'Hall effect sensor',
  'Hall probe',
  'Magnetic anomaly detector',
  'Magnetometer',
  'Magnetoresistance',
  'MEMS magnetic field sensor',
  'Metal detector',
  'Planar Hall sensor',
  'Radio direction finder',
  'Test light',
  'Voltage detector',
];

const EnvironmentalSensorWeatherStationTypes = [
  'Actinometer',
  'Air pollution sensor',
  'Bedwetting alarm',
  'Ceilometer',
  'Dew warning',
  'Electrochemical gas sensor',
  'Fish counter',
  'Frequency domain sensor',
  'Gas detector',
  'Hook gauge evaporimeter',
  'Humistor',
  'Hygrometer',
  'Leaf sensor',
  'Lysimeter',
  'Pyranometer',
  'Pyrgeometer',
  'Psychrometer',
  'Rain gauge',
  'Rain sensor',
  'Seismometer',
  'SNOTEL',
  'Snow gauge',
  'Soil moisture sensor',
  'Stream gauge',
  'Tide gauge',
  'Weather radar',
];

const FlowSensorTypes = [
  'Air flow meter',
  'Anemometer',
  'Flow sensor',
  'Gas meter',
  'Mass flow sensor',
  'Water meter',
];

const PositionDisplacementSensorTypes = [
  'Accelerometer',
  'Auxanometer',
  'Capacitive displacement sensor',
  'Capacitive sensing',
  'DetectionLoop',
  'Flex sensor',
  'Free fall sensor',
  'Gravimeter',
  'Gyroscopic sensor',
  'HeightDetectionDevice',
  'Impact sensor',
  'Inclinometer',
  'Incremental encoder',
  'Integrated circuit piezoelectric sensor',
  'Laser rangefinder',
  'Laser surface velocimeter',
  'LIDAR',
  'Linear encoder',
  'Linear variable differential transformer (LVDT)',
  'Liquid capacitive inclinometers',
  'Odometer',
  'Photoelectric sensor',
  'Piezoelectric accelerometer',
  'Position sensor',
  'Position sensitive device',
  'Angular rate sensor',
  'Rotary encoder',
  'Rotary variable differential transformer',
  'Selsyn',
  'Shock detector',
  'Shock data logger',
  'SpeedDetectionDevice',
  'Sudden Motion Sensor',
  'Tilt sensor',
  'Tachometer',
  'Ultrasonic thickness gauge',
  'Ultra-wideband radar',
  'Variable reluctance sensor',
  'Velocity receiver',
];

const OpticalCameraSensorTypes = [
  'Charge-coupled device',
  'CMOS sensor',
  'Angle–sensitive pixel',
  'Colorimeter',
  'Contact image sensor',
  'Electro-optical sensor',
  'Flame detector',
  'Infra-red sensor',
  'Kinetic inductance detector',
  'LED as light sensor',
  'Light-addressable potentiometric sensor',
  'Nichols radiometer',
  'Fiber optic sensors',
  'Optical position sensor',
  'Thermopile laser sensors',
  'Photodetector',
  'Photodiode',
  'Photomultiplier',
  'Photomultiplier tube',
  'Phototransistor',
  'Photoelectric sensor',
  'Photoionization detector',
  'Photoresistor',
  'Photoswitch',
  'Phototube',
  'Scintillometer',
  'Shack–Hartmann wavefront sensor',
  'Single-photon avalanche diode',
  'Superconducting nanowire single-photon detector',
  'Transition-edge sensor',
  'UVSensor',
  'Visible Light Photon Counter',
  'Wavefront sensor',
];

const PressureSensorTypes = [
  'Barograph',
  'Barometer',
  'Boost gauge',
  'Bourdon gauge',
  'Hot filament ionization gauge',
  'Ionization gauge',
  'McLeod gauge',
  'Oscillating U-tube',
  'Permanent downhole gauge',
  'Piezometer',
  'Pirani gauge',
  'Pressure sensor',
  'Pressure gauge',
  'Tactile sensor',
  'Time pressure gauge',
];

const DensitySensorTypes = [
  'Bhangmeter',
  'Hydrometer',
  'Force gauge and Force Sensor',
  'Level sensor',
  'Load cell',
  'Magnetic level gauge',
  'Nuclear density gauge',
  'Piezocapacitive pressure sensor',
  'Piezoelectric sensor',
  'Strain gauge',
  'Torque sensor',
  'Viscometer',
];

const TemperatureSensorTypes = [
  'Bolometer',
  'Bimetallic strip',
  'Calorimeter',
  'Exhaust gas temperature gauge',
  'Flame detection',
  'Gardon gauge',
  'Golay cell',
  'Heat flux sensor',
  'Infrared thermometer',
  'Microbolometer',
  'Microwave radiometer',
  'Net radiometer',
  'Quartz thermometer',
  'Resistance thermometer',
  'Silicon bandgap temperature sensor',
  'Special sensor microwave/imager',
  'Temperature gauge',
  'Thermistor',
  'Thermocouple',
  'Thermometer',
  'Pyrometer',
];

const ProximitySensorTypes = [
  'Alarm sensor',
  'Doppler radar',
  'Motion detector',
  'Occupancy sensor',
  'Proximity sensor',
  'Passive infrared sensor',
  'Reed switch',
  'Stud finder',
  'Triangulation sensor',
  'Touch switch',
  'Active pixel sensor',
  'Back-illuminated sensor',
  'BioFET',
  'Biochip',
  'Biosensor',
  'Capacitance probe',
  'Capacitance sensor',
  'Catadioptric sensor',
  'Carbon paste electrode',
  'Digital sensors',
  'Displacement receiver',
  'Electromechanical film',
  'Electro-optical sensor',
  'Electrochemical fatigue crack sensor',
  'Fabry–Pérot interferometer',
  'Fisheries acoustics',
  'Image sensor',
  'Image sensor format',
  'Inductive sensor',
  'Intelligent sensor',
  'Lab-on-a-chip',
  'Leaf sensor',
  'Machine vision',
  'Microelectromechanical systems',
  'MOSFET',
  'Photoelasticity',
  'Quantum sensor',
  'Radar',
  'Ground-penetrating radar',
  'Synthetic aperture radar',
  'Radar tracker',
  'Stretch sensor',
  'Sensor array',
  'Sensor fusion',
  'Sensor grid',
  'Sensor node',
  'Soft sensor',
  'Sonar',
  'Staring array',
  'Transducer',
  'Ultrasonic sensor',
  'Video sensor',
  'Visual sensor network',
  'Wheatstone bridge',
  'Wireless sensor network',
];

const OtherTypes = [
  'Actigraphy',
  'Air pollution sensor',
  'Analog image processing',
  'Atomic force microscopy',
  'Atomic Gravitational Wave Interferometric Sensor',
  'Attitude control (spacecraft): Horizon sensor, Earth sensor, Sun sensor',
  'Catadioptric sensor',
  'Chemoreceptor',
  'Compressive sensing',
  'Cryogenic particle detectors',
  'Dew warning',
  'Diffusion tensor imaging',
  'Digital holography',
  'Electronic tongue',
  'Fine Guidance Sensor',
  'FineDustSensor',
  'Flat panel detector',
  'Functional magnetic resonance imaging',
  'Glass break detector',
  'Heartbeat sensor',
  'Hyperspectral sensors',
  'IRIS (Biosensor), Interferometric Reflectance Imaging Sensor',
  'Laser beam profiler',
  'Littoral Airborne Sensor/Hyperspectral',
  'LORROS',
  'Millimeter wave scanner',
  'Magnetic resonance imaging',
  'Moire deflectometry',
  'Molecular sensor',
  'Nanosensor',
  'Nano-tetherball Sensor',
  'Omnidirectional camera',
  'Organoleptic sensors',
  'Optical coherence tomography',
  'Phase unwrapping techniques',
  'Polygraph Truth Detection',
  'Positron emission tomography',
  'Push broom scanner',
  'Quantization (signal processing)',
  'Range imaging',
  'Scanning SQUID microscope',
  'Single-Photon Emission Computed Tomography (SPECT)',
  'Smartdust',
  'SQUID, Superconducting quantum interference device',
  'SSIES, Special Sensors-Ions, Electrons, and Scintillation thermal plasma analysis package',
  'SSMIS, Special Sensor Microwave Imager / Sounder',
  'Structured-light 3D scanner',
  'Sun sensor, Attitude control (spacecraft)',
  'Superconducting nanowire single-photon detector',
  'Thin-film thickness monitor',
  'Time-of-flight camera',
  'TriDAR, Triangulation and LIDAR Automated Rendezvous and Docking',
  'Unattended Ground Sensors',
];

export const SensorTypes = [
  {
    name: 'Sound Sensor',
    types: SoundSensorTypes,
  }, {
    name: 'Chemical Sensor',
    types: ChemicalSensorTypes,
  }, {
    name: 'Electric Current Sensor',
    types: ElectricCurrentSensorTypes,
  }, {
    name: 'Environmental Sensor Weather Station',
    types: EnvironmentalSensorWeatherStationTypes,
  }, {
    name: 'Flow Sensor',
    types: FlowSensorTypes,
  }, {
    name: 'Position Displacement Sensor',
    types: PositionDisplacementSensorTypes,
  }, {
    name: 'Optical Camera Sensor',
    types: OpticalCameraSensorTypes,
  }, {
    name: 'Pressure Sensor',
    types: PressureSensorTypes,
  }, {
    name: 'Density Sensor',
    types: DensitySensorTypes,
  }, {
    name: 'Temperature Sensor',
    types: TemperatureSensorTypes,
  }, {
    name: 'Proximity Sensor',
    types: ProximitySensorTypes,
  }, {
    name: 'Other',
    types: OtherTypes,
  },
];
