apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-frontend
spec:
  selector:
    matchLabels:
      app: registry-frontend
  template:
    spec:
      containers:
      - image: sensrnet-registry-frontend_central-viewer:latest
        name: registry-frontend
        imagePullPolicy: Never
        resources: {}
