apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-frontend
spec:
  template:
    spec:
      containers:
      - image: sensrnet-registry-frontend_registry-frontend:latest
        name: registry-frontend
        imagePullPolicy: Never
        resources: {}
