apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-frontend
spec:
  template:
    spec:
      containers:
      - image: sensrnet-registry-frontend_registry-frontend:latest
        name: registry-frontend
        imagePullPolicy: Never
        resources: {}
        env:
          - name: OIDC_ISSUER
            value: http://localhost/dex
          - name: OIDC_WELL_KNOWN
            value: http://localhost/dex
          - name: OIDC_CLIENT_ID
            value: registry-frontend
