apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry-frontend
  name: registry-frontend
  namespace: sensrnet-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4200
  selector:
    app: registry-frontend
