export enum EventType {
    DeviceLocated = 'DeviceLocated',
    DeviceRelocated = 'DeviceRelocated',
    DeviceRegistered = 'DeviceRegistered',
    DeviceUpdated = 'DeviceUpdated',
    DeviceRemoved = 'DeviceRemoved',
    DatastreamAdded = 'DatastreamAdded',
    DatastreamUpdated = 'DatastreamUpdated',
    DatastreamRemoved = 'DatastreamRemoved',
    OrganizationRegistered = 'OrganizationRegistered',
    OrganizationUpdated = 'OrganizationUpdated',
    LegalEntityRemoved = 'LegalEntityRemoved',
    PublicContactDetailsAdded = 'PublicContactDetailsAdded',
    ContactDetailsUpdated = 'ContactDetailsUpdated',
    ContactDetailsRemoved = 'ContactDetailsRemoved',
}
